### PR TITLE
Some auth problems

### LINKED ISSUE #249: [Bug] JWT 验签前未做空值校验
### 问题描述

https://github.com/opanel-mc/opanel/blob/aa6625f9f624b7abea56cecb1bbf2b55429fac10/core/src/main/java/net/opanel/web/JwtManager.java#L42-L47

`jws.getHeader().getKeyId()`、`payload.getIssuer()`、`payload.getExpiration()`、`payload.get("access")` 任一为 `null` 都会 NPE。虽然外面 catch Exception 会兜住返回 `false`，但 stacktrace 会污染日志。

### 复现步骤

_No response_

### Minecraft版本

全版本

### OPanel版本

2.0.0-rc4

### 请确认以下事项

- [x] 我已确认以上事项

### LINKED ISSUE #250: [Bug] `AuthController`非原子失败计数
### 问题描述

https://github.com/opanel-mc/opanel/blob/aa6625f9f624b7abea56cecb1bbf2b55429fac10/core/src/main/java/net/opanel/controller/api/AuthController.java#L84-L89

以上代码对 `ConcurrentHashMap` 使用 get-then-put，并发失败登录会少计数。应使用 `merge` 或 `compute`。`validateCram` 也没像 `getCram` 那样校验当前 IP 是否在临时封禁中。

### 复现步骤

_No response_

### Minecraft版本

全版本

### OPanel版本

2.0.0-rc4

### 请确认以下事项

- [x] 我已确认以上事项

### PR DESCRIPTION
**Pull request by xiaoyangcc159**
close #249
close #250

### CODE REVIEW

**Review by NriotHrreion — CHANGES_REQUESTED** [review]
删掉注释，if后面不要有空格

File: core/src/main/java/net/opanel/controller/api/AuthController.java [hunk 1]
```diff
@@ -68,24 +53,24 @@ public AuthController(OPanel plugin) {
...
-            failedRecords.put(reqIp, current + 1);
-            if(current + 1 >= maxTries) {
-                temporaryBannedRecords.put(reqIp, System.currentTimeMillis() + bannedPeriod);
-                failedRecords.put(reqIp, 0);
+            final int current = incrementFailedCount(reqIp);
+            if(current >= maxTries) {
+                setTemporaryBan(reqIp);
             }
 
             plugin.logger.warn("A failed login request from "+ reqIp +" (Failed for "+ (current + 1) +" times)");
```
Comment (NriotHrreion) [inline core/src/main/java/net/opanel/controller/api/AuthController.java]:
```suggestion
            plugin.logger.warn("A failed login request from "+ reqIp +" (Failed for "+ current +" times)");
```

**Review by NriotHrreion — CHANGES_REQUESTED** [review]

**Review by NriotHrreion — APPROVED** [review]
LGTM
